complete -c code-minimap -n "__fish_use_subcommand" -s H -l horizontal-scale -d 'Specify horizontal scale factor'
complete -c code-minimap -n "__fish_use_subcommand" -s V -l vertical-scale -d 'Specify vertical scale factor'
complete -c code-minimap -n "__fish_use_subcommand" -l padding -d 'Specify padding width'
complete -c code-minimap -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c code-minimap -n "__fish_use_subcommand" -l version -d 'Prints version information'
complete -c code-minimap -n "__fish_use_subcommand" -f -a "completion" -d 'Generate shell completion file'
complete -c code-minimap -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c code-minimap -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Prints help information'
complete -c code-minimap -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Prints version information'
complete -c code-minimap -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c code-minimap -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
